### ISSUE TITLE
What is the difference between DDSM and VQ-Diffusion ?

### ISSUE THREAD

**Issue by peterdarkdarkgogo** [jzhoulab/ddsm#1]
What is the difference between DDSM and VQ-Diffusion ?

**Comment by PavelAvdeyev** [comment]
As far as I can tell, VQ-Diffusion model is based on a vector quantized variational autoencoder (VQ-VAE) whose latent space is modeled by a conditional variant of the recently developed Denoising Diffusion Probabilistic Model (DDPM). DDSM is a method based on Mutilivariate Jacobi Diffusion Process and does not use any variational autoencoders. The application is also completely different since we are focusing on biological sequence generation and not text-to-image generation. You can check our paper for more details: https://arxiv.org/abs/2305.10699
